import { addDays, formatISO } from "date-fns";
import type { UserSnapshot } from "@/types/domain";

const iso = (date: Date) => formatISO(date, { representation: "date" });

export function buildDemoSnapshot(userId = "demo-user"): UserSnapshot {
  const today = new Date();
  const firstOfNextMonth = new Date(
    today.getFullYear(),
    today.getMonth() + 1,
    1,
  );
  return {
    profile: {
      id: userId,
      email: "demo@moneynest.app",
      name: "Demo",
      onboarding_complete: true,
      created_at: new Date().toISOString(),
    },
    account: {
      id: "demo-account",
      user_id: userId,
      checking_balance: 1200,
      savings_balance: 850,
      updated_at: new Date().toISOString(),
    },
    income: [
      {
        id: "demo-income-1",
        user_id: userId,
        name: "Main Job",
        amount: 2100,
        frequency: "biweekly",
        next_payday: iso(addDays(today, 5)),
        created_at: new Date().toISOString(),
      },
    ],
    bills: [
      {
        id: "demo-bill-1",
        user_id: userId,
        name: "Rent",
        amount: 1200,
        due_date: iso(firstOfNextMonth),
        category: "Rent/Mortgage",
        autopay: false,
        status: "unpaid",
        notes: null,
        created_at: new Date().toISOString(),
      },
      {
        id: "demo-bill-2",
        user_id: userId,
        name: "Phone",
        amount: 85,
        due_date: iso(addDays(today, 3)),
        category: "Phone",
        autopay: true,
        status: "unpaid",
        notes: null,
        created_at: new Date().toISOString(),
      },
      {
        id: "demo-bill-3",
        user_id: userId,
        name: "Car Insurance",
        amount: 160,
        due_date: iso(addDays(today, 5)),
        category: "Insurance",
        autopay: false,
        status: "unpaid",
        notes: null,
        created_at: new Date().toISOString(),
      },
      {
        id: "demo-bill-4",
        user_id: userId,
        name: "Electric",
        amount: 120,
        due_date: iso(addDays(today, 8)),
        category: "Utilities",
        autopay: false,
        status: "unpaid",
        notes: null,
        created_at: new Date().toISOString(),
      },
      {
        id: "demo-bill-5",
        user_id: userId,
        name: "Credit Card",
        amount: 75,
        due_date: iso(addDays(today, 5)),
        category: "Credit Card",
        autopay: false,
        status: "unpaid",
        notes: null,
        created_at: new Date().toISOString(),
      },
    ],
    subscriptions: [
      sub(userId, "Netflix", 15.49, addDays(today, 2), "Streaming", "Review"),
      sub(userId, "Spotify", 10.99, addDays(today, 12), "Music", "Keep"),
      sub(userId, "Gym", 39.99, addDays(today, 4), "Fitness", "Review"),
      sub(userId, "iCloud", 2.99, addDays(today, 20), "Cloud Storage", "Keep"),
      sub(userId, "Amazon Prime", 14.99, addDays(today, 7), "Shopping", "Keep"),
    ],
    goals: [
      {
        id: "demo-goal-1",
        user_id: userId,
        name: "Emergency Fund",
        target_amount: 2000,
        current_amount: 850,
        monthly_target: 150,
        category: "Emergency Fund",
        created_at: new Date().toISOString(),
      },
      {
        id: "demo-goal-2",
        user_id: userId,
        name: "Vacation",
        target_amount: 1500,
        current_amount: 300,
        monthly_target: 100,
        category: "Vacation",
        created_at: new Date().toISOString(),
      },
    ],
    settings: {
      id: "demo-settings",
      user_id: userId,
      minimum_cushion: 100,
      currency: "USD",
      pay_frequency: "biweekly",
      dark_mode: false,
      notification_preferences: {},
      created_at: new Date().toISOString(),
    },
    financial_accounts: [
      {
        id: "demo-fa-1",
        user_id: userId,
        institution_name: "Chase",
        account_name: "Chase Checking",
        account_type: "checking",
        balance: 1200,
        currency: "USD",
        source: "manual",
        status: "manual",
        notes: null,
        plaid_item_id: null,
        plaid_account_id: null,
        include_in_safe_to_spend: true,
        last_synced_at: new Date().toISOString(),
        created_at: new Date().toISOString(),
        updated_at: new Date().toISOString(),
      },
      {
        id: "demo-fa-2",
        user_id: userId,
        institution_name: "Ally",
        account_name: "Ally Savings",
        account_type: "savings",
        balance: 850,
        currency: "USD",
        source: "manual",
        status: "manual",
        notes: null,
        plaid_item_id: null,
        plaid_account_id: null,
        include_in_safe_to_spend: false,
        last_synced_at: new Date().toISOString(),
        created_at: new Date().toISOString(),
        updated_at: new Date().toISOString(),
      },
      {
        id: "demo-fa-3",
        user_id: userId,
        institution_name: "Capital One",
        account_name: "Capital One Credit Card",
        account_type: "credit_card",
        balance: -640,
        currency: "USD",
        source: "manual",
        status: "manual",
        notes: null,
        plaid_item_id: null,
        plaid_account_id: null,
        include_in_safe_to_spend: false,
        last_synced_at: new Date().toISOString(),
        created_at: new Date().toISOString(),
        updated_at: new Date().toISOString(),
      },
    ],
    transactions: [
      // Chase Checking
      {
        id: "demo-tx-1",
        user_id: userId,
        financial_account_id: "demo-fa-1",
        plaid_transaction_id: null,
        name: "Whole Foods",
        merchant_name: "Whole Foods",
        amount: -54.23,
        category: "Groceries",
        transaction_date: iso(addDays(today, -2)),
        pending: false,
        source: "manual",
        notes: null,
        created_at: new Date().toISOString(),
      },
      {
        id: "demo-tx-2",
        user_id: userId,
        financial_account_id: "demo-fa-1",
        plaid_transaction_id: null,
        name: "Payroll",
        merchant_name: "Employer Inc.",
        amount: 2100,
        category: "Income",
        transaction_date: iso(addDays(today, -5)),
        pending: false,
        source: "manual",
        notes: "Biweekly paycheck",
        created_at: new Date().toISOString(),
      },
      // Ally Savings
      {
        id: "demo-tx-3",
        user_id: userId,
        financial_account_id: "demo-fa-2",
        plaid_transaction_id: null,
        name: "Interest",
        merchant_name: "Ally Bank",
        amount: 2.15,
        category: "Interest",
        transaction_date: iso(addDays(today, -10)),
        pending: false,
        source: "manual",
        notes: null,
        created_at: new Date().toISOString(),
      },
      // Capital One Credit Card
      {
        id: "demo-tx-4",
        user_id: userId,
        financial_account_id: "demo-fa-3",
        plaid_transaction_id: null,
        name: "Amazon",
        merchant_name: "Amazon",
        amount: -120.0,
        category: "Shopping",
        transaction_date: iso(addDays(today, -1)),
        pending: false,
        source: "manual",
        notes: "Online order",
        created_at: new Date().toISOString(),
      },
      {
        id: "demo-tx-5",
        user_id: userId,
        financial_account_id: "demo-fa-3",
        plaid_transaction_id: null,
        name: "Payment",
        merchant_name: "Capital One",
        amount: 100.0,
        category: "Payment",
        transaction_date: iso(addDays(today, -7)),
        pending: false,
        source: "manual",
        notes: "Credit card payment",
        created_at: new Date().toISOString(),
      },
    ],
  };
}

function sub(
  userId: string,
  name: string,
  amount: number,
  renewal: Date,
  category:
    | "Streaming"
    | "Music"
    | "Cloud Storage"
    | "Fitness"
    | "Apps"
    | "Shopping"
    | "Other",
  status: "Keep" | "Cancel" | "Review",
) {
  return {
    id: `demo-sub-${name.toLowerCase().replace(/\s+/g, "-")}`,
    user_id: userId,
    name,
    amount,
    renewal_date: iso(renewal),
    category,
    status,
    notes: null,
    created_at: new Date().toISOString(),
  };
}

export function emptySnapshot(userId = "demo-user"): UserSnapshot {
  return {
    profile: {
      id: userId,
      email: null,
      name: null,
      onboarding_complete: false,
      created_at: new Date().toISOString(),
    },
    account: {
      id: "local-account",
      user_id: userId,
      checking_balance: 0,
      savings_balance: 0,
      updated_at: new Date().toISOString(),
    },
    income: [],
    bills: [],
    subscriptions: [],
    goals: [],
    settings: {
      id: "local-settings",
      user_id: userId,
      minimum_cushion: 100,
      currency: "USD",
      pay_frequency: "biweekly",
      dark_mode: false,
      notification_preferences: {},
      created_at: new Date().toISOString(),
    },
    financial_accounts: [],
    transactions: [],
  };
}
